#!/usr/bin/env bash

PATTERN="^openjdk-([0-9.]+)_agent-([0-9.]+)$"

if [[ "$SOURCE_BRANCH" =~ $PATTERN ]]; then
  OPENJDK_VERSION="${BASH_REMATCH[1]}"
  JENKINS_AGENT_VERSION="${BASH_REMATCH[2]}"

  docker build \
    --build-arg OPENJDK_VERSION=$OPENJDK_VERSION \
    --build-arg JENKINS_AGENT_VERSION=$JENKINS_AGENT_VERSION \
    -f $DOCKERFILE_PATH \
    -t $IMAGE_NAME \
    .
else 
  docker build \
    -f $DOCKERFILE_PATH \
    -t $IMAGE_NAME \
fi